version: '3.5'
services:
  i2b2-medco:
    image: medco/i2b2-medco:v0.1
    build:
      context: ../..
      dockerfile: deployment/i2b2-medco/Dockerfile
      target: release
    environment:
    - I2B2_DB_HOST=postgresql
    - I2B2_DB_PORT=5432
    - I2B2_DB_USER=i2b2
    - I2B2_DB_PW=i2b2
    - I2B2_DB_NAME=i2b2medco
    - WILDFLY_ADMIN_PASSWORD=admin
    - I2B2_DOMAIN_NAME=i2b2medco
    - I2B2_SERVICE_PASSWORD=pFjy3EjDVwLfT2rB9xkK
    - DEFAULT_USER_PASSWORD=demouser
    - NODE_IDX=0
    - UNLYNX_DEBUG_LEVEL=1
    - AXIS2_LOGLEVEL=INFO
    volumes:
    - ./configuration-profile:/medco-configuration
